### ISSUE TITLE
Add limit options for fetching jobs

### ISSUE THREAD

**Issue by Ginden** [darky/bull-repl#12]
I have `3631530` failed jobs right now. Using just `failed` just cause process to hang forever. I would like to see only few failed jobs, by specyfing eg. `--limit 100` (or defaulting to printing only subset).

**Comment by darky** [comment]
PR welcome on `take` and `skip` flags

**Comment by darky** [comment]
`0.20.0` and `1.1.0` (bull mq) fixed
