### ISSUE TITLE
Problem with port forwarding

### ISSUE THREAD

**Issue by jamesholcomb** [darky/bull-repl#14]
I have a BullMQ + redis instance in k8s that I am trying to connect to

First I port forward:

kubectl port-forward --namespace default svc/redis-master 54321:6379 &

Then with bull-repl@next:

> BULL-REPL> connect -r redis://localhost:54321 my-queue
> Handling connection for 54321
> connect ECONNREFUSED 127.0.0.1:6379
> BULL-REPL> (node:812) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
> (node:812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)

I can connect ok with `rdcli`

~$ rdcli -p 54321
127.0.0.1:54321> Handling connection for 54321

127.0.0.1:54321>

**Comment by darky** [comment]
Maybe this can help you
https://github.com/luin/ioredis/issues/1036

**Comment by jamesholcomb** [comment]
Thanks @darky I'll take a look.

**Comment by jamesholcomb** [comment]
The thread seems to suggest using `bind 0.0.0.0` in the redis config.  I use the bitnami helm chart which already does this.

I tried testing with a simple ioredis@4.16.0 setup using the port forwarding from above (`rdcli` does not use ioredis):

```
const Redis = require("ioredis")

const redis = new Redis("redis://localhost:54321")

redis.info().then((res) => {
  console.log(res)

  process.exit(0)
})
```
output was
```
Handling connection for 54321
# Server
redis_version:5.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:3259c77a1d3a0c8d
redis_mode:standalone
os:Linux 4.14.138+ x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.3.0
process_id:1
run_id:04681e84ee9177cde753db0ec7ee744b2a643a17
tcp_port:6379
uptime_in_seconds:49342
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:5111033
executable:/opt/bitnami/redis/bin/redis-server
config_file:/opt/bitnami/redis/etc/redis.conf
```

If I do bull-repl connect -r 127.0.0.1:54321 myqueue, it connects, but it is my local macOS redis instance, not the one port forwarded on k8s.

**Comment by darky** [comment]
Thanks! I will bump `1.1.1`, when go home

**Comment by trathailoi** [comment]
> The thread seems to suggest using `bind 0.0.0.0` in the redis config. I use the bitnami helm chart which already does this.
> 
> I tried testing with a simple ioredis@4.16.0 setup using the port forwarding from above (`rdcli` does not use ioredis):
> 
> ```
> const Redis = require("ioredis")
> 
> const redis = new Redis("redis://localhost:54321")
> 
> redis.info().then((res) => {
>   console.log(res)
> 
>   process.exit(0)
> })
> ```
> 
> output was
> 
> ```
> Handling connection for 54321
> # Server
> redis_version:5.0.7
> redis_git_sha1:00000000
> redis_git_dirty:0
> redis_build_id:3259c77a1d3a0c8d
> redis_mode:standalone
> os:Linux 4.14.138+ x86_64
> arch_bits:64
> multiplexing_api:epoll
> atomicvar_api:atomic-builtin
> gcc_version:6.3.0
> process_id:1
> run_id:04681e84ee9177cde753db0ec7ee744b2a643a17
> tcp_port:6379
> uptime_in_seconds:49342
> uptime_in_days:0
> hz:10
> configured_hz:10
> lru_clock:5111033
> executable:/opt/bitnami/redis/bin/redis-server
> config_file:/opt/bitnami/redis/etc/redis.conf
> ```
> 
> If I do bull-repl connect -r 127.0.0.1:54321 myqueue, it connects, but it is my local macOS redis instance, not the one port forwarded on k8s.

I'm using the bitnami helm chart, and getting the same issue. Have you found any solution for this yet ? Please share if you have one. Thank you in advance!

**Comment by jamesholcomb** [comment]
Are you on @latest or @next?
