### ISSUE TITLE
Some standard CLI shortcuts are missing

### ISSUE THREAD

**Issue by pierpo** [darky/bull-repl#19]
Not critical but it feels like these shortcuts should be present as they are on other tools.

- `CTRL-N` should be the same as up arrow
- `CTRL-P` should be the same as down arrow

You can see that the `node` CLI uses these shortcuts 😊 (as well as `python`... and many others)

**Comment by darky** [comment]
Hello, @pierpo.
It out of scope for me. I doubt that **vorpal** have support of this feature.
And implement some hack for this don't want.
But you can try to implement PR for this feature :)

**Comment by pierpo** [comment]
Oh sorry, didn't notice it was based on vorpal :blush: 
Indeed it is vorpal's responsibility.

Thank you and thanks for the great job!

**Comment by darky** [comment]
Unfortunately, vorpal.js is dead project :)

**Comment by pierpo** [comment]
Haha okay! I guess it'll remain a dead issue, it's really nothing anyway 😄
