### ISSUE TITLE
Feature request: Queue as command line argument

### ISSUE THREAD

**Issue by spitlo** [darky/bull-repl#21]
Hi!

One feature I think would be helpful is the ability to add the name of the queue you want to connect to when you invoke the command, like `bull-repl my-bull-queue`.

This would allow us to have a generalized command in package.json that is the same across multiple projects, f ex `yarn queue` or `yarn bull` that resolves to `bull-repl project-specific-queue`. That would cut down on the time it would take to get up and running (browsing through code to find the name of the queue + the connect step).

**Comment by darky** [comment]
`0.23.0` and `1.4.0` fixed
You can predefine startup command, when start bull-repl. For example: `bull-repl connect my-queue`
