### ISSUE TITLE
A proper format of command 'clean'.

### ISSUE THREAD

**Issue by coderisimo** [darky/bull-repl#22]
I was tried many variations and still get **Incorrect period** error. Can you provide a simple example of this command? Thank you!

**Comment by darky** [comment]
```
BULL-REPL> clean --help

  Missing required argument. Showing Help:

  Usage: clean [options] <period>

  Clean queue for period ago, period format - ms

  Options:

    --help                 output usage information
    -s, --status <status>  Status of the job to clean, default: completed
    -l, --limit <limit>    Maximum amount of jobs to clean per call, default: all
```

`ms` here is link to https://github.com/vercel/ms#examples, where examples (`10h` - 10 hours ago, `2 days` - 2 days ago, e. t. .c)

**Comment by coderisimo** [comment]
Thanks a lot! 
I tried `clean  ms('5h')` and `clean  "ms('5h')"` . But it should be  just  `clean 10h`,
Spasibo- na zdorovie!
