### ISSUE TITLE
Turn back -u option for connect in 0.x.x version

### ISSUE THREAD

**Issue by wundo** [darky/bull-repl#24]
On several issues (#13, #18, #8) people mention the -r option, but I can't get it to work on 0.24:

```
BULL-REPL> connect --help

  Missing required argument. Showing Help:

  Usage: connect [options] <queue>

  Connect to bull queue

  Options:

    --help                 output usage information
    --prefix <prefix>      Prefix to use for all queue jobs
    -h, --host <host>      Redis host for connection
    -p, --port <port>      Redis port for connection
    -d, --db <db>          Redis db for connection
    --password <password>  Redis password for connection
    -c, --cert <cert>      Absolute path to pem certificate if TLS used
```

```
BULL-REPL> connect --redis redis://u:p@h:6379 queue
  Invalid option: 'redis'. Showing Help:
...
```

```
BULL-REPL> connect -r redis://u:p@h:6379 queue
  Invalid option: 'r'. Showing Help:
...
```

What am I doing wrong?

**Comment by darky** [comment]
`--redis` option was removed since `0.22.0` version due to implicit format, which cause questions about it.
Please use explicit options `--host`, `--port`, `--db`, `--password` (maybe `--cert`) for success connection.

**Comment by wundo** [comment]
@darky any plans on adding it back? 

That would be really handy when connecting to heroku/dokku enviroments because it allow us to connect using the enviroment vars.

**Comment by jamesholcomb** [comment]
This was added back with the `-u` param in v0.24

`bull-repl connect -u redis://localhost:6379 myqueue`

EDIT: Looks like the -u option only landed in 1.5.0

**Comment by wundo** [comment]
@darky can we get it back ported to 0.x?

**Comment by darky** [comment]
@wundo feel free to make PR

Need to implement dynamic `Queue` constructor 
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue

If passed `-u` param, use it as second argument. Otherwise, need to pass `RedisOpts` in third argument.

Place to change:
https://github.com/darky/bull-repl/blob/cbf8141d45d4f2a35e557d3d0db1990a93d70dc7/src/queue.ts#L41

**Comment by darky** [comment]
`0,27.0`
