### ISSUE TITLE
Filter jobs list

### ISSUE THREAD

**Issue by morheal** [darky/bull-repl#27]
Im trying to filter completed jobs list by timestamp with `completed --filter='{"timestamp": 2020-07-09T13:57:32.701Z}'`
Surely Im doing something wrong, which syntax I need to use?

**Comment by darky** [comment]
`completed --help` show you:

```
  Usage: completed [options]

  Fetch completed jobs

  Options:

    --help                   output usage information
    -f, --filter <filter>    Filter jobs via searchjs (https://github.com/deitch/searchjs#examples)
    -t, --timeAgo <timeAgo>  Get jobs since time ago via ms (https://github.com/zeit/ms#examples)
    -s, --start <start>      Start index (pagination)
    -e, --end <end>          End index (pagination)

```

Ok, you can see examples on https://github.com/deitch/searchjs#examples about format

Try something like: `completed --filter '{"timestamp": {"from": 1594313511000}}'`, where number is count of milliseconds
