### ISSUE TITLE
Filter output to only show specific fields

### ISSUE THREAD

**Issue by davestimpert** [darky/bull-repl#30]
Especially with large jobs, listing jobs fills up the whole screen and it is difficult to show a list of multiple jobs.  It would be nice to have the option to grep the output of completed, failed, etc with something like grep or jq https://stedolan.github.io/jq/manual/#Basicfilters

**Comment by darky** [comment]
Feel free to use power of **jq** with `--query` option since `0.25.0` or `1.6.0`
