### ISSUE TITLE
The 'node-jq'  is necessary?

### ISSUE THREAD

**Issue by skyblue** [darky/bull-repl#31]
```
Building jq from https://github.com/stedolan/jq/releases/download//jq-1.6/jq-1.6.tar.gz
Error: Command failed: /bin/sh -c autoreconf -fi
configure.ac:36: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:36: error: possibly undefined macro: AM_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1


    at /usr/lib/node_modules/bull-repl/node_modules/execa/index.js:231:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0) {
  code: 1,
  killed: false,
  stdout: '',
  stderr: "configure.ac:36: warning: macro 'AM_PROG_LIBTOOL' not found in library\n" +
    'configure.ac:36: error: possibly undefined macro: AM_PROG_LIBTOOL\n' +
    '      If this token and others are legitimate, please use m4_pattern_allow.\n' +
    '      See the Autoconf documentation.\n' +
    'autoreconf: /usr/bin/autoconf failed with exit status: 1\n',
  failed: true,
  signal: null,
  cmd: '/bin/sh -c autoreconf -fi',
  timedOut: false
}
```

This is too complicated.

**Comment by darky** [comment]
Try this solutions:
https://github.com/sanack/node-jq/issues/174

**Comment by davestimpert** [comment]
It seems like that doesn't work because then node-jq/bin is missing...  here's the error I get when trying to use jq:

events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn ****/node-jq/1.11.1/node_modules/node-jq/bin/jq ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by darky** [comment]
@skyblue @davestimpert, which OS you use?
@skyblue seems you don't have some build tools and jq can't be installed. 
Here answer: https://github.com/darky/bull-repl/issues/31#issuecomment-669057665
You can try install some build tools or install jq manually and skip it, when install bull-repl via `NODE_JQ_SKIP_INSTALL_BINARY=true`
@davestimpert seems you have similar problem, did have similar error log of @skyblue ?
I test it on OS X and Arch linux, all fine.

**Comment by darky** [comment]
Note: If you use `NODE_JQ_SKIP_INSTALL_BINARY=true` and install own `jq`, need to use `JQ_PATH` for path of your own `jq`

**Comment by davestimpert** [comment]
> Note: If you use `NODE_JQ_SKIP_INSTALL_BINARY=true` and install own `jq`, need to use `JQ_PATH` for path of your own `jq`

Ah ha, JQ_PATH is what I needed.  I set that environment variable and now it is working.  I didn't find a working example in the docs, so for anyone else that needs a starting point, here's a command that works for me to get the id and timestamp of each completed job.

`completed -q '[.root[] | {id: .id, ts: .timestamp}]'`

**Comment by skyblue** [comment]
Actually, I mean, can use other simpler libraries instead？

**Comment by darky** [comment]
@skyblue, suggest your variant with causes, why it should be
