### ISSUE TITLE
Scripting: eg, clean all jobs from cron

### ISSUE THREAD

**Issue by tombh** [darky/bull-repl#32]
Thanks for building this.

I'd like to be able to clean all jobs in a queue from a script. I see that I can at least `connect` in a single line, ie, `bull-repl connect`, but there doesn't seem to be a way to run another command after that? I have to go in as a human and manually type the command to clean a queue myself.

**Comment by darky** [comment]
@tombh feel free to add `--exec` option to `connect` command
If it passed, use direct exec like this:
https://github.com/darky/bull-repl/blob/04d40c2505f64e8078e3dbcb7e98fd89386316e0/index.ts#L398-L400

**Comment by darky** [comment]
`0.27.0`, `1.8.0`
