### ISSUE TITLE
`node-jq` package is quite strange - it calls `/bin/sh -c autoreconf -fi` when installing packages

### ISSUE THREAD

**Issue by nodkz** [darky/bull-repl#33]
It may be a vulnerability

<img width="1027" alt="Screen Shot 2020-08-18 at 22 23 00" src="https://user-images.githubusercontent.com/1946920/90539420-9a201700-e1a1-11ea-87e6-5206312967d7.png">

cc @davestimpert

**Comment by darky** [comment]
https://github.com/darky/bull-repl/issues/31#issuecomment-669962402
https://github.com/darky/bull-repl/issues/31#issuecomment-670532790

here answers
