### ISSUE TITLE
Connection fails if HOST is not 127.0.0.1 using direct connect

### ISSUE THREAD

**Issue by cdesiles** [darky/bull-repl#35]
Hi!

thank you for your tool!
I was trying it, and figured out there is an error with slightly different use cases:

1.
```sh
$ bull-repl connect --host $REDIS_HOST myqueue
BULL-REPL> 
connect ECONNREFUSED 127.0.0.1:6379
BULL-REPL> (node:322) UnhandledPromiseRejectionWarning: connect ECONNREFUSED 127.0.0.1:6379
(Use `node --trace-warnings ...` to show where the warning was created)
...
```

2.
```sh
$ bull-repl
BULL-REPL> connect --host 10.170.165.172 myqueue
Connected to 10.170.165.172:6379, prefix: bull, queue: myqueue

BULL-REPL | bull.myqueue>
```

Do you have a clue on this?
Thank you,

**Comment by jamesholcomb** [comment]
Can you verify the value of $REDIS_HOST?

**Comment by darky** [comment]
Hello! Try to echo variable like this:
`bull-repl connect --host $(echo $REDIS_HOST) myqueue`

**Comment by cdesiles** [comment]
Hi,
thank you for your replies, here it is:

```
$ echo $REDIS_HOST
10.170.165.172
```

```
$ bull-repl connect --host $(echo $REDIS_HOST) myqueue
BULL-REPL> 
connect ECONNREFUSED 127.0.0.1:6379
BULL-REPL> (node:168) UnhandledPromiseRejectionWarning: connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by cdesiles** [comment]
I don't think this is a question here, this is much more an issue with the tool itself, which may not have been tried with a different redis host than localhost.

**Comment by darky** [comment]
Try `0.26.3` or `1.7.3`, should be fixed

**Comment by cdesiles** [comment]
This now works, thank you very much!
