### ISSUE TITLE
Extend options for "add" command

### ISSUE THREAD

**Issue by edu791** [darky/bull-repl#37]

**Comment by darky** [comment]
Now exists only one option `name`
Example: `add --name test '{"x": 1}'`

**Comment by edu791** [comment]
@darky Is it possible to pass the job ID and the number of retries?

**Comment by darky** [comment]
Possible, feel free to add PR.
It's not hard, API of bull very simple
https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queueadd

**Comment by darky** [comment]
Done via https://github.com/darky/bull-repl/pull/50
