### ISSUE TITLE
Can't find /usr/local/bin/node

### ISSUE THREAD

**Issue by TimonVS** [darky/bull-repl#4]
I get the following error when running bull-repl:

```sh
λ ~/ bull-repl
/Users/timon/.asdf/lib/commands/shim-exec.sh: /Users/timon/.asdf/installs/nodejs/10.16.0/.npm/bin/bull-repl: /usr/local/bin/node: bad interpreter: No such file or directory
/Users/timon/.asdf/lib/commands/shim-exec.sh: line 26: /Users/timon/.asdf/installs/nodejs/10.16.0/.npm/bin/bull-repl: Undefined error: 0
```

I suspect this happens because of hashbangify in [the build script](https://github.com/darky/bull-repl/blob/master/package.json#L27). Hashbangify looks at your local setup which may not be the same as everyone else's, I think it should just be `#!/usr/bin/env node` :)

**Comment by darky** [comment]
Cool ok, will do it.
You can save my time via PR ;)

**Comment by darky** [comment]
https://github.com/darky/bull-repl/commit/86e763c421f3ec0651b5aadf273c6ba935d26aad
