### ISSUE TITLE
Syntax for clean

### ISSUE THREAD

**Issue by SaucyJack** [darky/bull-repl#40]
How can I use the "clean" command to clean everything in the "failed" status of a queue? I've tried all manner of different things...

`clean -s failed`

`clean --status="failed"`

...and it never works, always displays the help topic.

**Comment by darky** [comment]
```
BULL-REPL | bull.qwe> clean -s failed

  Missing required argument. Showing Help:       // 1*

  Usage: clean [options] <period>      // 2*

  Clean queue for period ago, period format - https://github.com/zeit/ms#examples     // 3*

  Options:

    --help                 output usage information
    -s, --status <status>  Status of the job to clean, default: completed
    -l, --limit <limit>    Maximum amount of jobs to clean per call, default: all

```

On line 1* you can see, that cli tool properly say you about missing required argument
On line 2* you can see, that \<period\> is require argument
On line 3* you can see some examples (need click to link) of \<period\> format

**Comment by SaucyJack** [comment]
For anyone who hits on this question in the future, if you want to include state and period, do not use the "ms()" call in the period examples. So, to clean everything in the last 24 hours from the "failed" state:

`clean -s failed 24h`

**Comment by patrik-csak** [comment]
trying bull-repl for the first time today and `clean` is not working for me :

<img width="464" alt="CleanShot 2023-01-06 at 11 29 59@2x" src="https://user-images.githubusercontent.com/4766244/211085856-1d0cd56b-f06d-4ae9-8e56-39b8274bb9e7.png">

<details>
<summary>(text of screenshot for accessibility and seo)</summary>
<pre><code>
BULL-REPL | bull.update-playlist> stats
┌───────────┬────────┐
│  (index)  │ Values │
├───────────┼────────┤
│  waiting  │   0    │
│  active   │   2    │
│ completed │   0    │
│  failed   │   4    │
│  delayed  │   0    │
│  paused   │   0    │
└───────────┴────────┘
BULL-REPL | bull.update-playlist> clean -l 10 -s failed -y 24h
Assuming yes for Clean
Jobs cleaned
BULL-REPL | bull.update-playlist> stats
┌───────────┬────────┐
│  (index)  │ Values │
├───────────┼────────┤
│  waiting  │   0    │
│  active   │   2    │
│ completed │   0    │
│  failed   │   4    │
│  delayed  │   0    │
│  paused   │   0    │
└───────────┴────────┘
</pre></code>
</details>

**Comment by darky** [comment]
@ptrkcsk maybe your failed jobs fail less than 24h ago?

**Comment by patrik-csak** [comment]
it's not working for recently created jobs, but maybe it's because there's no `finishedOn` date?


```
❯ date -u  
Fri Jan  6 19:41:57 UTC 2023

❯ bull-repl
BULL-REPL> connect-to update-playlist
Connected to localhost:6379, prefix: bull, queue: update-playlist
BULL-REPL | bull.update-playlist> stats
┌───────────┬────────┐
│  (index)  │ Values │
├───────────┼────────┤
│  waiting  │   0    │
│  active   │   1    │
│ completed │   0    │
│  failed   │   0    │
│  delayed  │   0    │
│  paused   │   0    │
└───────────┴────────┘
BULL-REPL | bull.update-playlist> active
[
  {
    id: '1',
    data: { id: 1 },
    timestamp: 2023-01-06T19:39:57.086Z,
    processedOn: 2023-01-06T19:39:57.087Z,
    finishedOn: undefined,
    name: '__default__',
    failedReason: undefined,
    stackTrace: [],
    returnValue: null,
    attemptsMade: 0,
    delay: 0,
    progress: 0
  }
]
count: 1
BULL-REPL | bull.update-playlist> clean -s active -y 1d
Assuming yes for Clean
Jobs cleaned
BULL-REPL | bull.update-playlist> stats
┌───────────┬────────┐
│  (index)  │ Values │
├───────────┼────────┤
│  waiting  │   0    │
│  active   │   1    │
│ completed │   0    │
│  failed   │   0    │
│  delayed  │   0    │
│  paused   │   0    │
└───────────┴────────┘
BULL-REPL | bull.update-playlist>
```

**Comment by darky** [comment]
You try to clean jobs, which created 24 hours ago
Try to pass `1m` for cleaning jobs, which created 1 minute ago

**Comment by patrik-csak** [comment]
ah, it cleans jobs *before* `<period>`, not after. thanks, @darky !
