### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/bull-repl/node_modules/node-jq/……

### ISSUE THREAD

**Issue by lakerchen** [darky/bull-repl#42]
I have got errors like this when I install bull-repl，what is going wrong with this？

[root@VM_10_186_centos ~]# npm install bull-repl@next -g
npm WARN deprecated @hapi/joi@16.1.8: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/formula@1.2.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pinpoint@1.0.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
/usr/local/bin/bull-repl -> /usr/local/lib/node_modules/bull-repl/index.js

> core-js@2.6.12 postinstall /usr/local/lib/node_modules/bull-repl/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> node-jq@1.11.2 postinstall /usr/local/lib/node_modules/bull-repl/node_modules/node-jq
> npm run install-binary

> node-jq@1.11.2 install-binary /usr/local/lib/node_modules/bull-repl/node_modules/node-jq
> node scripts/install-binary.js

Building jq from https://github.com/stedolan/jq/releases/download//jq-1.6/jq-1.6.tar.gz
[Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/bull-repl/node_modules/node-jq/d51835be-fc7e-4faf-b374-64aef47a544d'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/bull-repl/node_modules/node-jq/d51835be-fc7e-4faf-b374-64aef47a544d'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jq@1.11.2 install-binary: `node scripts/install-binary.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jq@1.11.2 install-binary script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-jq@1.11.2 postinstall: `npm run install-binary`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-jq@1.11.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-27T16_29_25_471Z-debug.log

**Comment by darky** [comment]
try sudo

**Comment by darky** [comment]
also https://github.com/darky/bull-repl/issues/31#issuecomment-670532790
