### ISSUE TITLE
Upgrade bull dependency

### ISSUE THREAD

**Issue by emcsween** [darky/bull-repl#44]
Hi there,

Thanks for this very useful tool! We've recently had an issue with the cleanup operation, which quickly gets very expensive as the queue size grows. Because it has the potential to block the Redis server for hours, it makes it dangerous to use bull-repl on a production server. I've suggested a [fix](https://github.com/OptimalBits/bull/pull/2326) to the Bull library and it has been integrated in version 4.8.1.

Would it be possible to bump the bull dependency to the latest version in bull-repl?

Thanks!

Eric

**Comment by darky** [comment]
`0.27.1`
