### ISSUE TITLE
Can't add new job - getting Object.fromEntries is not a function error

### ISSUE THREAD

**Issue by pauloabq** [darky/bull-repl#51]
Wen try to add a new job using

`add '{"cnpj": "12345678901234"}'`

Getting error `Object.fromEntries is not a function`

Because of this https://github.com/darky/bull-repl/pull/50?

**Comment by darky** [comment]
You use node.js 10?
https://nodejs.org/en/about/releases/

**Comment by darky** [comment]
Please upgrade your node.js to 16 LTS
Or better to 18 current, it will be LTS in October
