### ISSUE TITLE
Connect command `-r` flag seems to be broken

### ISSUE THREAD

**Issue by michaeldfallen** [darky/bull-repl#8]
On v0.15.0 the following command would work:

```
BULL-REPL> connect -r redis://user:pass@host:port queue
```

Since v0.16.0 that command fails with: 

```
Error: getaddrinfo ENOTFOUND redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
```

I've replicated on all versions since v0.15.0

**Comment by darky** [comment]
Please try this command: `connect -r user:pass@host:port queue`

**Comment by darky** [comment]
Feel free to use `0.17.2` for command like `connect -r redis://user:pass@host:port queue`

**Comment by yofriadi** [comment]
I think the example on how to connect need to be provided on the help command and in README

**Comment by darky** [comment]
`0.17.3` with improved doc
